name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'
      - name: Build with Maven
        run: |
          mvn -f SpringBootHelloWorld --batch-mode --update-snapshots package
          mkdir staging && cp SpringBootHelloWorld/target/*.jar staging
      - name: Persist workflow data as artifacts
        uses: actions/upload-artifact@v2
        with:
           name: github-actions-artifact
           path: staging
      - name: Publish package
        run: mvn -f SpringBootHelloWorld --batch-mode deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
