name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'
      - name: Build with Maven
        run: |
          mvn -f SpringBootHelloWorld --batch-mode --update-snapshots package
          mkdir staging && cp SpringBootHelloWorld/target/*.jar staging
      - name: Persist workflow data as artifacts
        uses: actions/upload-artifact@v2
        with:
           name: github-actions-artifact
           path: staging
      - name: Publish the packages
        run: mvn -f SpringBootHelloWorld --batch-mode deploy -X
        env:
          GITHUB_TOKEN: ${{ secrets.TEST_TOKEN }}
      - name: Deleting the Package
        uses: actions/delete-package-versions@v4
        with: 
            owner: 'Shreelmc'
            package-name: 'SpringBootHelloWorld.com.javainuse.springboothelloworld'
            package-type: 'maven'
            token: ${{ secrets.TEST_TOKEN }}
            min-versions-to-keep: 2
            delete-only-pre-release-versions: "true"
